name: ci
on: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: 'ReactAvancado/reactavancado.client/package-lock.json'
          
      - name: Install dependencies
        run: npm install
        working-directory: ReactAvancado/reactavancado.client

      - name: Linting
        run: npm run lint
        working-directory: ReactAvancado/reactavancado.client

      - name: Testing
        run: npm run test:ci
        working-directory: ReactAvancado/reactavancado.client

      - name: Build
        run: npm run build
        working-directory: ReactAvancado/reactavancado.client
