name: ci
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node in Project Directory
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org' #Optional, but good practice.
        shell: bash
        run: |
          cd ReactAvancado/reactavancado.client
          npm config set cache /home/runner/.npm
          npm config set prefix $(pwd)/.local-npm
          npm install

      - name: Linting
        run: npm run lint

      - name: Testing
        run: npm run test:ci

      - name: Build
        run: npm run build
